export 'clubs_page.dart';
export 'course_details_page.dart';
export 'courses_page.dart';
export 'home_page.dart';
export 'info_page.dart';
export 'modification_page.dart';
export 'notifications_page.dart';
export 'order_status_page.dart';
export 'rating_page.dart';
